/**
 * A very small XML reader.
 *
 * Office formats and EPUB are ZIP archives of XML, and what we need from them
 * is narrow: find elements by name, read attributes, collect text. A full
 * conformant XML parser is a large dependency to carry for that, and the files
 * we read are machine-generated by Word, PowerPoint and Sigil rather than
 * hand-written, so the awkward corners of XML (custom entities, DTDs,
 * processing instructions with markup inside) do not arise.
 *
 * The tradeoff is stated rather than hidden: if this parser cannot make sense
 * of a document, the adapter records an `unknown` and the rules report
 * `cantTell`. It never guesses at structure it could not read.
 */

export interface XmlNode {
  readonly name: string;
  readonly attrs: Readonly<Record<string, string>>;
  readonly children: readonly XmlNode[];
  /** Direct text content of this element, excluding descendants. */
  readonly text: string;
}

const VOID_SELF_CLOSING = /\/\s*>$/;

function decodeEntities(value: string): string {
  return value
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    // A reference to a code point that does not exist (or a number too large
    // to be one) must degrade to a placeholder, never throw: String.fromCodePoint
    // raises RangeError on out-of-range input, and one crafted `&#x110000;`
    // inside a document part would otherwise crash the whole audit.
    .replace(/&#(\d+);/g, (_, code: string) => safeCodePoint(Number.parseInt(code, 10), 10))
    .replace(/&#x([0-9a-f]+);/gi, (_, code: string) => safeCodePoint(parseInt(code, 16), 16))
    // Ampersand last, or the replacements above would re-decode their output.
    .replace(/&amp;/g, '&');
}

function safeCodePoint(code: number, _radix: number): string {
  if (!Number.isFinite(code) || code < 0 || code > 0x10ffff) return '\uFFFD';
  // Surrogates are not assignable in well-formed content; the replacement
  // character keeps the pipeline alive rather than throwing.
  if (code >= 0xd800 && code <= 0xdfff) return '\uFFFD';
  try {
    return String.fromCodePoint(code);
  } catch {
    return '\uFFFD';
  }
}

function parseAttributes(source: string): Record<string, string> {
  // Null-prototype: attribute names come from the file, and a plain object
  // would quietly do something strange with `__proto__` and `constructor`.
  const attrs: Record<string, string> = Object.create(null);
  const pattern = /([\w:.-]+)\s*=\s*("([^"]*)"|'([^']*)')/g;
  let match: RegExpExecArray | null;
  while ((match = pattern.exec(source)) !== null) {
    const name = match[1] as string;
    if (name === '__proto__' || name === 'constructor' || name === 'prototype') continue;
    const value = match[3] ?? match[4] ?? '';
    attrs[name] = decodeEntities(value);
  }
  return attrs;
}

interface MutableNode {
  name: string;
  attrs: Record<string, string>;
  children: MutableNode[];
  text: string;
}

/**
 * Parse a document into a tree. Returns null when the input is not usable —
 * the caller must then record an `unknown` rather than assume an empty file.
 */
export function parseXml(source: string): XmlNode | null {
  /*
   * DTDs are stripped rather than honoured: we never resolve entities, so the
   * internal subset is inert either way, and dropping it keeps the tokenizer
   * from having to understand `<!ENTITY ...>` at all.
   *
   * The strip is a bounded scan, not a regex: an earlier version used
   * `/<!DOCTYPE[^>[]*(\[[\s\S]*?\])?[^>]*>/` which backtracks quadratically
   * on a long DOCTYPE with no closing bracket - a small crafted file could
   * burn minutes of CPU. A linear indexOf walk cannot.
   */
  const cleaned = source
    .replace(/<\?[\s\S]*?\?>/g, '')
    .replace(/<!--[\s\S]*?-->/g, '');
  let withoutDoctype = cleaned;
  for (;;) {
    const start = withoutDoctype.search(/<!DOCTYPE/i);
    if (start === -1) break;
    const bracket = withoutDoctype.indexOf('[', start);
    const close = withoutDoctype.indexOf('>', start);
    if (bracket !== -1 && bracket < close) {
      // Internal subset: skip to the matching `]`, then past the `>`.
      const endBracket = withoutDoctype.indexOf(']', bracket);
      const after = endBracket === -1 ? withoutDoctype.length : endBracket + 1;
      const end = withoutDoctype.indexOf('>', after);
      withoutDoctype =
        end === -1
          ? withoutDoctype.slice(0, start)
          : withoutDoctype.slice(0, start) + withoutDoctype.slice(end + 1);
    } else {
      withoutDoctype =
        close === -1
          ? withoutDoctype.slice(0, start)
          : withoutDoctype.slice(0, start) + withoutDoctype.slice(close + 1);
    }
  }

  const root: MutableNode = { name: '#root', attrs: {}, children: [], text: '' };
  const stack: MutableNode[] = [root];
  /*
   * The tokenizer is iterative, but the tree it builds is later walked and
   * frozen recursively. Capping nesting depth at parse time is the one place
   * that protects every downstream consumer: a crafted 100k-deep `<a><a>…`
   * part is truncated here rather than overflowing a stack later. Machine-
   * generated Office/XML content sits in the tens, so 500 is generous.
   */
  const MAX_DEPTH = 500;
  let truncatedDepth = false;

  const tokens = /<([^>]+)>|([^<]+)/g;
  let match: RegExpExecArray | null;

  while ((match = tokens.exec(withoutDoctype)) !== null) {
    const tag = match[1];
    const text = match[2];
    const current = stack[stack.length - 1];
    if (!current) break;

    if (text !== undefined) {
      const decoded = decodeEntities(text);
      // Preserve significant whitespace inside runs of text but do not let
      // indentation between elements become content.
      if (decoded.trim().length > 0) current.text += decoded;
      else if (current.text.length > 0 && !current.text.endsWith(' ')) current.text += ' ';
      continue;
    }

    if (tag === undefined) continue;

    if (tag.startsWith('/')) {
      const name = tag.slice(1).trim();
      // Tolerate mismatched closes rather than abandoning the document.
      for (let i = stack.length - 1; i > 0; i -= 1) {
        if (stack[i]?.name === name) {
          stack.length = i;
          break;
        }
      }
      continue;
    }

    if (tag.startsWith('!')) continue;

    const selfClosing = VOID_SELF_CLOSING.test(`<${tag}>`);
    const body = selfClosing ? tag.replace(/\/\s*$/, '') : tag;
    const name = (body.match(/^[\w:.-]+/) ?? [''])[0];
    if (name.length === 0) continue;

    const child: MutableNode = {
      name,
      attrs: parseAttributes(body.slice(name.length)),
      children: [],
      text: '',
    };
    current.children.push(child);
    if (!selfClosing) {
      if (stack.length < MAX_DEPTH) stack.push(child);
      else truncatedDepth = true;
    }
  }

  if (root.children.length === 0) return null;
  if (truncatedDepth) {
    return null;
  }
  return freeze(root);
}

function freeze(node: MutableNode): XmlNode {
  return {
    name: node.name,
    attrs: node.attrs,
    children: node.children.map(freeze),
    text: node.text.replace(/\s+/g, ' ').trim(),
  };
}

// ── Queries ──────────────────────────────────────────────────────────────────

/** Local name, ignoring the namespace prefix (`w:p` → `p`). */
export function localName(name: string): string {
  const colon = name.indexOf(':');
  return colon === -1 ? name : name.slice(colon + 1);
}

export function* walkXml(node: XmlNode): Generator<XmlNode> {
  yield node;
  for (const child of node.children) yield* walkXml(child);
}

/** All descendants whose local name matches, in document order. */
export function findAll(node: XmlNode, name: string): XmlNode[] {
  const wanted = localName(name);
  return [...walkXml(node)].filter((candidate) => localName(candidate.name) === wanted);
}

export function findFirst(node: XmlNode, name: string): XmlNode | null {
  return findAll(node, name)[0] ?? null;
}

/** Direct children matching a local name. */
export function childrenNamed(node: XmlNode, name: string): XmlNode[] {
  const wanted = localName(name);
  return node.children.filter((child) => localName(child.name) === wanted);
}

/** Attribute lookup that ignores the namespace prefix on the attribute name. */
export function attr(node: XmlNode, name: string): string | null {
  const direct = node.attrs[name];
  if (direct !== undefined) return direct;

  const wanted = localName(name);
  for (const [key, value] of Object.entries(node.attrs)) {
    if (localName(key) === wanted) return value;
  }
  return null;
}

/** All text under a node, in document order. */
export function allText(node: XmlNode): string {
  const parts: string[] = [];
  for (const current of walkXml(node)) {
    if (current.text.length > 0) parts.push(current.text);
  }
  return parts.join(' ').replace(/\s+/g, ' ').trim();
}
